### ISSUE TITLE
wrong AUX starting height

### ISSUE THREAD

**Issue by tpfuemp** [nyancoin-official/nyancoin-client#9]
AUX starting height has only been set in Testnet-Params.

Mainnet is unchanged, so AUX not active

**Comment by nyancoin-official** [comment]
@tpfuemp Ok folks I see where I fucked up. Left vim open after I made then change, then pushed to Shithub. File and changes were *saved* but only to /tmp and didn't get pushed. 😂😂😂

**Comment by Shinoa-Fores** [comment]
New height fixed in https://github.com/nyancoin-official/nyancoin-client/commit/97ba95a3f0c419988a37470ceba259911de367fb 
Old version didn't push all the files, apologies.
